name: Permission Escalation Request Form
description: Request Updated Permissions
title: "[PERM-REQ]: (FILL IN HERE)"
labels: requires-approval
assignees: arolek-glovebox, sethmoeckel-glovebox, sethr-gb
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the permission escalation request
    validations:
      required: true

  - type: textarea
    id: users
    attributes:
      label: List of users to escalate
      description: Include the email and/or user name relevant for the request
    validations:
      required: true

  - type: textarea
    id: business_justification
    attributes:
      label: Describe the business justification
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Environment
      description: Select which environment(s) the request is associated with
      options:
      - label: Production
      - label: Development
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Application or environment
      description: Indicate which application(s) the request is associated with
      options:
      - label: Application (i.e. Glovebox admin)
      - label: Amazon Web Services
      - label: GitHub
      - label: Twilio
      - label: Segment
      - label: Netlify
      - label: Other
    validations:
      required: true
