name: White Label UI Request
description: Submit a request to create or update a white-labeled UI for web, iOS, and/or Android platforms for an agency.
title: "White Label - Agency Name - SLA Date"
assignees: ["brian-glovebox", "Carlos-glovebox"]
body:
  - type: markdown
    attributes:
      value: |
        ## White Label UI Request
        Use this template to submit requirements for a white-labeled product for web, iOS, and Android platforms. Please provide all required details to ensure timely processing. Note that some fields are shared across platforms, while others are platform-specific.
  - type: input
    id: agency-name
    attributes:
      label: Agency Name
      description: Provide the name of the agency for this request.
      placeholder: e.g., Primal Insurance
    validations:
      required: true
  - type: input
    id: sla-date
    attributes:
      label: SLA Date
      description: Specify the Service Level Agreement (SLA) due date for this request (e.g., MM-DD).
      placeholder: e.g., 08-01
    validations:
      required: true
  - type: input
    id: color
    attributes:
      label: Color Scheme
      description: Specify the primary color scheme for the white-labeled UI (e.g., sky). This applies to all platforms.
      placeholder: e.g., sky
    validations:
      required: true
  - type: input
    id: web-svg-logo
    attributes:
      label: SVG Logo
      description: Provide a link to the SVG logo file or attach it to this issue (https://www.adobe.com/express/feature/image/convert/svg).
      placeholder: e.g., URL or file name
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Web-Specific Requirements
        Provide the following details for the white-labeled web application. Note: Store listing must be set up before handling this request.
  - type: input
    id: web-favicon
    attributes:
      label: Favicon
      description: Provide a link to the favicon file or attach it to this issue (https://favicon.io/).
      placeholder: e.g., URL or file name
    validations:
      required: true
  - type: input
    id: web-qr-code
    attributes:
      label: QR Code
      description: Provide a link to the QR code image or attach it to this issue (this can only be done once the app stores are set up).
      placeholder: e.g., Drop File here
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Native App Requirements (iOS and Android)
        Provide the following details for the white-labeled iOS and Android apps. Some fields apply to both platforms.
  - type: input
    id: native-app-icon
    attributes:
      label: App Icon
      description: Provide a link to the app icon issue from agency-app-assets.
      placeholder: e.g., Github App Icon Issue
    validations:
      required: true
  - type: textarea
    id: native-screenshots
    attributes:
      label: Screenshots
      description: Provide 2-8 screenshots showcasing app content (JPEG or 24-bit PNG, no alpha; min 320px, max 3840px on shortest/longest side; 16:9 or 9:16 aspect ratio). List links to files or attach them. Note: Images must showcase app content, not just promotional material.
      placeholder: e.g., screenshot1.jpg, screenshot2.png
    validations:
      required: false
  - type: input
    id: native-app-name
    attributes:
      label: App Name
      description: Specify the app name (max 30 characters).
      placeholder: e.g., Example Agency App
    validations:
      required: true
  - type: input
    id: native-short-description
    attributes:
      label: Short App Description
      description: Provide a short app description (max 80 characters). Recommended: "Download our app today to access your policies and documents anytime, anywhere.".
      placeholder: e.g., Access your policies anytime, anywhere.
    validations:
      required: true
  - type: textarea
    id: native-full-description
    attributes:
      label: Full App Description
      description: Provide a full app description (max 4,000 characters). e.g. "Having your insurance with an independent agent is amazing! Managing your insurance however can be frustrating. With GloveBox, now you have the ability to manage your insurance with direct-to-carrier and direct-to-agent access in a single app!"
      placeholder: Enter the full description here.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Android-Specific Requirements
        Provide the following details specific to the Android app.
  - type: input
    id: android-promo-image
    attributes:
      label: High-Resolution Promo Image (Optional)
      description: Provide a link to the high-resolution promo image (1024 x 500 pixels, JPEG or 24-bit PNG, no alpha) or attach it to this issue. The feature graphic can be repurposed if desired.
      placeholder: e.g., URL or file name
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## iOS-Specific Requirements
        Provide any iOS-specific requirements below. If not applicable, leave blank or note "TBD."
  - type: checkbox
    id: ios-api-key
    attributes:
      label: iOS Api Key
      description: Has the iOS API key been created?
    validations:
      required: false
  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Add any additional notes, instructions, or context for this white label request.
      placeholder: e.g., Specific design preferences, priority level, etc.
    validations:
      required: false